# Needed for libsodium
dist: xenial
sudo: required

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

env:
  - SKIP_NETWORK_TESTS=0

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsodium-dev
install:
    - travis_retry pip install tox
    # XXX Avoid snapcraft from loading useless libs when running on Ubuntu
    - sudo truncate -s 0 /etc/os-release
script:
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
    - if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
